copy /Y *.txt C:\input\peazip-9.8.0.src\dev\
copy /Y #times C:\input\peazip-9.8.0.src\dev\
copy /Y comp_speed C:\input\peazip-9.8.0.src\dev\
copy /Y history C:\input\peazip-9.8.0.src\dev\
copy /Y manifest C:\input\peazip-9.8.0.src\dev\
copy /Y readme C:\input\peazip-9.8.0.src\dev\
copy /Y *.aes C:\input\peazip-9.8.0.src\dev\
copy /Y *.asm C:\input\peazip-9.8.0.src\dev\
copy /Y *.bat C:\input\peazip-9.8.0.src\dev\
copy /Y *.c C:\input\peazip-9.8.0.src\dev\
copy /Y *.cnt C:\input\peazip-9.8.0.src\dev\
copy /Y *.crc C:\input\peazip-9.8.0.src\dev\
copy /Y *.hlp C:\input\peazip-9.8.0.src\dev\
copy /Y *.dfm C:\input\peazip-9.8.0.src\dev\
copy /Y *.diz C:\input\peazip-9.8.0.src\dev\
copy /Y *.dof C:\input\peazip-9.8.0.src\dev\
copy /Y *.dpr C:\input\peazip-9.8.0.src\dev\
copy /Y *.eng C:\input\peazip-9.8.0.src\dev\
copy /Y *.fca C:\input\peazip-9.8.0.src\dev\
copy /Y *.ger C:\input\peazip-9.8.0.src\dev\
copy /Y *.lrs C:\input\peazip-9.8.0.src\dev\
copy /Y *.manifest C:\input\peazip-9.8.0.src\dev\
copy /Y *.obj C:\input\peazip-9.8.0.src\dev\
copy /Y *.or C:\input\peazip-9.8.0.src\dev\
copy /Y *.rc C:\input\peazip-9.8.0.src\dev\
copy /Y *.res C:\input\peazip-9.8.0.src\dev\
copy /Y *.tf C:\input\peazip-9.8.0.src\dev\
copy /Y *.tph C:\input\peazip-9.8.0.src\dev\
copy /Y *.utl C:\input\peazip-9.8.0.src\dev\
copy /Y *.ico C:\input\peazip-9.8.0.src\dev\
copy /Y *.ini C:\input\peazip-9.8.0.src\dev\
copy /Y *.lfm C:\input\peazip-9.8.0.src\dev\
copy /Y *.lpi C:\input\peazip-9.8.0.src\dev\
copy /Y *.lpr C:\input\peazip-9.8.0.src\dev\
copy /Y *.inc C:\input\peazip-9.8.0.src\dev\
copy /Y *.pas C:\input\peazip-9.8.0.src\dev\
copy /Y *.zip C:\input\peazip-9.8.0.src\dev\
copy /Y *.7z C:\input\peazip-9.8.0.src\dev\
