#pragma once

#define ADD_7Z_COMMAND_ARGS L"Add7z", g_add_7z_icon_path, L"-add2multi7z "
#define ADD_7Z_ENCRYPT_COMMAND_ARGS L"Encrypt7z", g_lock_icon_path, L"-add2multi7zencrypt "
#define ADD_ARCHIVE_COMMAND L"AddArchive", g_add_archive_icon_path, L"-add2multi "
#define ADD_GZ_COMMAND_ARGS L"AddGZip", g_add_archive_icon_path, L"-add2multigz "
#define ADD_SEPARATE_ARCHIVE_COMMAND_ARGS L"AddToSeparateArchive", g_add_archive_icon_path, L"-add2multiseparate "
#define ADD_SFX_COMMAND_ARGS L"AddToSelfExtracting", g_add_sfx_icon_path, L"-add2multisfx "
#define ADD_XZ_COMMAND_ARGS L"AddXz", g_add_archive_icon_path, L"-add2multixz "
#define ADD_ZIP_COMMAND_ARGS L"AddZip", g_add_zip_icon_path, L"-add2multizip "
#define ADD_ZIP_MAIL_COMMAND_ARGS L"AddToZipAndMail", g_mail_icon_path, L"-add2multizipmail "
#define ADD_ZSTD_COMMAND_ARGS L"AddZstd", g_add_archive_icon_path, L"-add2multizstd "
#define BROWSE_ARCHIVE_COMMAND_ARGS L"OpenArchive", g_main_app_icon_path, L"-ext2browseasarchive "
#define CONVERT_COMMAND_ARGS L"Convert", g_convert_icon_path, L"-add2multiconvert "
#define EXTRACT_FOLDER_COMMAND_ARGS L"ExtFolder", g_extract_folder_icon_path, L"-ext2multifolder "
#define EXTRACT_HERE_COMMAND_ARGS L"ExtHere", g_extract_icon_path, L"-ext2multihere "
#define EXTRACT_MAIN_COMMAND_ARGS L"Ext", g_extract_icon_path, L"-ext2multi "
#define EXTRACT_SMART_COMMAND_ARGS L"ExtSmart", g_extract_folder_icon_path, L"-ext2multismart "
#define EXTRACT_TEST_COMMAND_ARGS L"Test", g_test_icon_path, L"-ext2test "
#define SPLIT_COMMAND_ARGS L"SplitFile", g_sprit_icon_path, L"-add2multisplit "
#define WIPE_COMMAND_ARGS L"SecureDelete", g_delete_icon_path, L"-add2wipe "
